#pragma once

#include "order.hpp"
#include "order_book.hpp"

#include <atomic>
#include <deque>
#include <memory>
#include <mutex>
#include <optional>
#include <unordered_map>
#include <vector>

namespace engine {

class MatchingEngine {
public:
    MatchingEngine();

    // ── Main entry point ──────────────────────────────────────────────────
    // Thread-safe. Returns all trades generated by this order.
    std::vector<Trade> process_order(std::shared_ptr<Order> order);

    // ── Cancel by ID (bypasses process_order) ─────────────────────────────
    bool cancel_by_id(const std::string& order_id);

    // ── Accessors ─────────────────────────────────────────────────────────
    OrderBook&       book()       { return _book; }
    const OrderBook& book() const { return _book; }

    std::optional<Trade> last_trade() const;
    std::vector<Trade>   recent_trades(int n = 50) const;

    // ── Stats ─────────────────────────────────────────────────────────────
    uint64_t total_orders_processed() const { return _total_orders.load(); }
    uint64_t total_trades_executed()  const { return _total_trades.load(); }
    double   total_volume_traded()    const { return _total_volume.load(); }
    double   uptime_seconds()         const;

private:
    OrderBook  _book;
    mutable std::mutex _mtx;

    // Trade log (newest first, capped at 10 000)
    std::deque<Trade> _trade_log;
    static constexpr std::size_t TRADE_LOG_MAX = 10'000;

    // Order registry (for cancel lookups that don't go through the book index)
    std::unordered_map<std::string, std::shared_ptr<Order>> _orders;

    // Stats (atomic so readers outside the lock can sample them cheaply)
    std::atomic<uint64_t> _total_orders{0};
    std::atomic<uint64_t> _total_trades{0};
    std::atomic<double>   _total_volume{0.0};
    double _start_time_unix;

    // ── Internal helpers (called under lock) ──────────────────────────────
    std::vector<Trade> _match_limit (std::shared_ptr<Order> order);
    std::vector<Trade> _match_market(std::shared_ptr<Order> order);
    Trade              _execute_match(Order& aggressor, Order& resting);
    void               _record_trade(const Trade& t);
};

} // namespace engine
